#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "=== Deployment Guard ==="
echo "pwd: $(pwd)"

if [ -f "$REPO_ROOT/package-lock.json" ]; then
  echo "Cleaning root package-lock.json (auto-generated by platform)"
  rm -f "$REPO_ROOT/package-lock.json"
fi

if [ -d "$REPO_ROOT/node_modules" ]; then
  echo "Cleaning root node_modules/ (auto-generated by platform)"
  rm -rf "$REPO_ROOT/node_modules"
fi

if [ ! -f "$REPO_ROOT/ggvibe/package.json" ]; then
  echo "FATAL: ggvibe/package.json not found!"
  exit 1
fi

if [ ! -f "$REPO_ROOT/ggvibe/package-lock.json" ]; then
  echo "FATAL: ggvibe/package-lock.json not found!"
  exit 1
fi

echo "PASS: Building from ggvibe/ only."
echo "==========================="
