import Link from "next/link";

export default function TermsPage() {
  return (
    <main style={{
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #0f0f23 0%, #1a1a2e 50%, #16213e 100%)',
      color: 'white',
      padding: '40px 20px',
    }}>
      <div style={{ maxWidth: '800px', margin: '0 auto' }}>
        <Link href="/" style={{ color: '#00d4ff', textDecoration: 'none', marginBottom: '24px', display: 'inline-block' }}>
          &larr; Back to Home
        </Link>

        <h1 style={{ color: '#00d4ff', marginBottom: '32px' }}>Terms of Service</h1>

        <div style={{ lineHeight: 1.8, color: 'rgba(255,255,255,0.85)' }}>
          <p><strong>Last updated:</strong> {new Date().toLocaleDateString()}</p>

          <h2 style={{ color: '#00d4ff', marginTop: '32px' }}>1. Acceptance of Terms</h2>
          <p>
            By accessing and using GGVIBE LIVE AI, you agree to be bound by these Terms of Service.
            If you do not agree to these terms, please do not use our service.
          </p>

          <h2 style={{ color: '#00d4ff', marginTop: '32px' }}>2. Description of Service</h2>
          <p>
            GGVIBE LIVE AI provides an AI-powered chat assistant that allows users to have
            natural language conversations, receive assistance, and generate content using
            artificial intelligence technology.
          </p>

          <h2 style={{ color: '#00d4ff', marginTop: '32px' }}>3. User Accounts</h2>
          <p>
            To access certain features, you must sign in using Google OAuth. You are responsible
            for maintaining the security of your account and all activities under your account.
          </p>

          <h2 style={{ color: '#00d4ff', marginTop: '32px' }}>4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the service for any illegal or unauthorized purpose</li>
            <li>Attempt to circumvent security measures or access restrictions</li>
            <li>Generate harmful, abusive, or inappropriate content</li>
            <li>Share your account credentials with others</li>
            <li>Use the service to harm or harass others</li>
          </ul>

          <h2 style={{ color: '#00d4ff', marginTop: '32px' }}>5. AI-Generated Content</h2>
          <p>
            Content generated by the AI assistant is provided for informational purposes.
            We do not guarantee the accuracy, completeness, or reliability of AI responses.
            Users should verify important information from authoritative sources.
          </p>

          <h2 style={{ color: '#00d4ff', marginTop: '32px' }}>6. Intellectual Property</h2>
          <p>
            The GGVIBE LIVE AI service, including its design, features, and content,
            is protected by intellectual property laws. You retain ownership of content
            you create using the service.
          </p>

          <h2 style={{ color: '#00d4ff', marginTop: '32px' }}>7. Limitation of Liability</h2>
          <p>
            GGVIBE LIVE AI is provided &quot;as is&quot; without warranties of any kind.
            We are not liable for any damages arising from your use of the service.
          </p>

          <h2 style={{ color: '#00d4ff', marginTop: '32px' }}>8. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the
            service after changes constitutes acceptance of the new terms.
          </p>

          <h2 style={{ color: '#00d4ff', marginTop: '32px' }}>9. Contact</h2>
          <p>
            For questions about these Terms of Service, please contact us through the
            GGVIBE LIVE AI platform.
          </p>
        </div>
      </div>
    </main>
  )
}
